name: AST Scanner plugin CI

on: [pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CX_BASE_URI: ${{ secrets.CX_BASE_URI}}
      CX_BASE_AUTH_URI: ${{ secrets.CX_BASE_AUTH_URI}}
      CX_TENANT: ${{ secrets.CX_TENANT }}
      CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
      CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run tests with coverage
        run: mvn test jacoco:report

      - name: Print total number of covered lines
        run: |
          COVERED_LINES=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" target/site/jacoco/jacoco.xml)
          echo "Total number of covered lines: $COVERED_LINES"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco

